module.exports = {
  'env': {
    'browser': true,
    'commonjs': true,
    'es6': true,
    'node': true,
    'jest': true,
  },
  'parser': 'babel-eslint',
  'parserOptions': {
    'sourceType': 'module'
  },
  'rules': {
    // 'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'block-scoped-var': 'warn',
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'camelcase': ['error', {'properties': 'always'}],
    'comma-dangle': ['error', 'only-multiline'],
    'comma-spacing': ['error', { 'before': false, 'after': true }],
    'comma-style': ['error', 'last'],
    'curly': 'error',
    'eqeqeq': 'warn',
    'indent': ['error', 2, { 'SwitchCase': 1 }],
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 2 }],
    'no-alert': 'warn',
    'no-array-constructor': 'error',
    'no-console': ['warn', { allow: ['error'] }],
    'no-const-assign': 'error',
    'no-debugger': 'error',
    'no-duplicate-imports': 'error',
    'no-empty': 'warn',
    'no-inline-comments': 'warn',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-new': 'error',
    'no-spaced-func': 'warn',
    'no-undefined': 'warn',
    'no-undef': 'error',
    'no-unused-expressions': ['error', { 'allowShortCircuit': true, 'allowTernary': true }],
    'no-unused-vars': 'warn',
    'no-use-before-define': ['error', { 'functions': false }],
    'no-var': 'error',
    'object-curly-spacing': ['warn', 'always'],
    'object-shorthand': 'error',
    'padding-line-between-statements': ['error', 
      { 'blankLine': 'always', 'prev': '*', 'next': 'return' },
      { 'blankLine': 'always', 'prev': ['const', 'let', 'var'], 'next': '*' },
      { 'blankLine': 'any', 'prev': ['const', 'let', 'var'], 'next': ['const', 'let', 'var'] },
      { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
      { 'blankLine': 'any', 'prev': 'directive', 'next': 'directive' },
    ],
    'semi': ['error', 'never'],
    'semi-spacing': ['error', { 'before': false, 'after': true }],
    'space-before-blocks': 'error',
    'space-before-function-paren': ['error', { 'anonymous': 'always', 'named': 'never' }],
    'space-infix-ops': ['error'],
    'switch-colon-spacing': ['error', { 'after': true, 'before': false }],
    'valid-jsdoc': ['warn', { 'requireReturn': false }],
    'strict': 0
  }
}
